name: Publish
on:
    push:
        tags:
            - release/*
jobs:
  build:
    name: Github Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish new version to Github packages
      uses: actions/setup-node@v1
      with:
        node-version: 16
        registry-url: 'https://npm.pkg.github.com/'
    - run: yarn install
    - run: yarn build
    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

