name: Publish
on:
    push:
        tags:
            - release/*
jobs:
  build:
    name: Github Package
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        always-auth: true
        registry-url: 'https://npm.pkg.github.com/'
        scope: '@onesilq'
    - run: yarn install
    - run: ls && pwd
    - run: yarn build:css
    - run: yarn build:js
    - run: ls && pwd
    - run: yarn styleguidist build
    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

