name: Publish
on:
    push:
        tags:
            - release/*
jobs:
  build:
    name: NPM Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Publish new version to NPM
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'
    - run: yarn install
    - run: yarn build:css
    - run: yarn build:js
    - run: yarn styleguidist build
    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}