name: Publish to npm
on:
    push:
        tags:
            - release/*
jobs:
  build:
    name: NPM Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Publish new version to NPM
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'
    - run: yarn install
    - run: yarn build:css
    - run: yarn build:js
    - run: yarn styleguidist build
    - name: Get version from package.json
      id: get_version
      run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
    - name: Publish to npm
      run: |
        if [[ "${{ steps.get_version.outputs.VERSION }}" == *"alpha"* ]]; then
          yarn publish --tag alpha
        else
          yarn publish
        fi
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}